
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.follower_name }}
spec:
  serviceName: "factomd-backup"
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: factomd
      role: {{ .Values.label_for_follower }}
  template:
    metadata:
      labels:
        app: factomd
        role: {{ .Values.label_for_follower }}
    spec:      
      containers:
        - name: factomd-follower
          image: {{ .Values.follower_image }} 
          command: ["sh", "-c"]
          args: ["/go/bin/factomd \
                  --loglvl='error' \
                  --sim_stdin=false \
                  --debuglog='network|process|dbsig|invalid|faulting|badmsgs' \
                  --debugconsole=remotehost \
                  --customnet=devnet \
                  --network=CUSTOM \
                  --stdoutlog out.txt \
                  --stderrlog out.txt \
                  --blktime=600"]
          volumeMounts:
           - name: {{ .Values.volume_name }}
             mountPath: /root/.factom/m2
           - name: config
             mountPath: "/root/.factom/m2/factomd.conf"
             subPath: "factomd.conf"
          ports:
           - containerPort: 8090
             name: control-panel
           - containerPort: 8093
             name: sim-control
           - containerPort: 8088
             name: factomd
           - containerPort: 8108
             name: explorer
             protocol: TCP
           - containerPort: 9876
             name: prometheus
             protocol: TCP
      volumes:
      - name: config
        secret:
          secretName: b-follower-config
          key: factomd.conf
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.volume_name }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10G

