apiVersion: batch/v1
kind: Job
metadata:
  name: gcs-restore-control
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: gcs-restore-control
          image: gcr.io/connect-dev-223719/gcs-restore-control
          volumeMounts:
          - name: service
            mountPath: "/service"
            readOnly: true
          env:
            - name: GCS_BUCKET
              value: "factomd-backup"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/service/service.json"
      volumes:
      - name: service
        secret:
          secretName: service-account
  backoffLimit: 0
